### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by RNPhelan** [swkidd/zacks-earnings#1]
Nice package and you seem to be getting it off the ground. Though, your tutorial doesn't show how to import the package. Have you tried this yourself? Because you have a "-" in the package name it causes an issue on my end (as that is an illegal character for naming purposes). Try changing "-" to "_" as so many package authors do. Cheers!

**Comment by hacpro** [comment]
the whole project dosent work. even if you import like: 
`import importlib
zack = importlib.import_module("zacks-earnings")`

you cant access the class.. I dont think this ever worked.. waste of time

**Comment by swkidd** [comment]
Thank you for checking out my repo and sorry for the inconvenience. Unfortunately I won't be able to update the pip package, but feel free to use the code file as is in any of your own projects / packages.
